
init_dir=~/.bash.d/init

export HISTFILESIZE=10000
export HISTSIZE=500

# Don't put duplicate lines in the history and do not add lines that start with a space
export HISTCONTROL=erasedups:ignoredups:ignorespace
export EDITOR=vim

shopt -s cdspell

# Show me the size (sorted) of only the folders in this directory
alias folders="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn"

source $init_dir/functions.bash
source $init_dir/platform.bash
source $init_dir/this_machine.bash
source $init_dir/work.bash

PROMPT_COMMAND=__prompt_command # prompt function is in functions.bash

